FROM node:alpine

WORKDIR /var/app

COPY package.json ./

RUN yarn install --only=prod

COPY . .

ENV PORT 3000 
ENV NODE_ENV development
#ENV DBHOST mongodb://docker.mongodb:27017/test

EXPOSE 3000 

CMD ["yarn", "start"]
